# Generated by Django 4.1.13 on 2024-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
