# Generated by Django 4.1.13 on 2024-05-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_friends_remove_profile_is_friend_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
