# Generated by Django 4.1.13 on 2024-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_friends_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.profile'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
