# Generated by Django 4.1.13 on 2024-05-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
