# Generated by Django 4.1.13 on 2024-05-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='count',
        ),
    ]
