# Generated by Django 4.1.13 on 2024-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_friendrequest_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='old_receiver_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='old_sender_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='old_receiver_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='old_sender_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='old_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
