# Generated by Django 4.1.13 on 2024-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_friendrequest_old_receiver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='old_receiver_id',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='old_sender_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='old_receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='old_sender_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_id',
        ),
    ]
